Rule: Update apple-cn proxy

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -42,7 +42,7 @@ jobs:
 
       - name: Download meta ruleset
         run: |
-          domain_lists=('category-httpdns-cn' 'apple@cn' 'apple' 'microsoft@cn' 'onedrive' 'microsoft' 'category-ai-!cn' 'amazon' 'shopify' 'category-ecommerce' 'paypal' 'wise' 'category-cryptocurrency' 'category-games@cn' 'category-games' 'reddit' 'discord' 'whatsapp' 'line' 'instagram' 'facebook' 'telegram' 'twitter' 'signal' 'meta' 'tiktok' 'bilibili' 'googlefcm' 'youtube' 'google' 'spotify' 'twitch' 'bahamut' 'hbo' 'disney' 'primevideo' 'netflix' 'speedtest' 'tld-!cn' 'category-pt' 'tracker' 'category-anticensorship' 'gfw' 'geolocation-!cn' 'private' 'cn' 'nga' 'xiaohongshu' 'sina' 'zhihu' 'douban' 'coolapk')
+          domain_lists=('category-httpdns-cn' 'apple' 'microsoft@cn' 'onedrive' 'microsoft' 'category-ai-!cn' 'amazon' 'shopify' 'category-ecommerce' 'paypal' 'wise' 'category-cryptocurrency' 'category-games@cn' 'category-games' 'reddit' 'discord' 'whatsapp' 'line' 'instagram' 'facebook' 'telegram' 'twitter' 'signal' 'meta' 'tiktok' 'bilibili' 'googlefcm' 'youtube' 'google' 'spotify' 'twitch' 'bahamut' 'hbo' 'disney' 'primevideo' 'netflix' 'speedtest' 'tld-!cn' 'category-pt' 'tracker' 'category-anticensorship' 'gfw' 'geolocation-!cn' 'private' 'cn' 'nga' 'xiaohongshu' 'sina' 'zhihu' 'douban' 'coolapk')
 
           for list in "${domain_lists[@]}"; do
               curl -f -L "${mihomo_domains}/${list}.list" | sed '$a\' > "download/meta/${list}.list" || { echo "Download Failed: ${list}.list"; exit 1; }
@@ -86,6 +86,7 @@ jobs:
               'httpdns.list https://github.com/VirgilClyne/GetSomeFries/raw/refs/heads/main/ruleset/HTTPDNS.Block.list'
               'pcdn.list https://github.com/uselibrary/PCDN/raw/refs/heads/main/pcdn.list'
               'adrules.list https://github.com/Cats-Team/AdRules/raw/refs/heads/main/adrules-surge.conf'
+              'global.list https://github.com/SukkaW/Surge/raw/refs/heads/master/Source/non_ip/global.conf'
           )
           for file in "${files[@]}"; do
               set -- $file
@@ -100,19 +101,22 @@ jobs:
               'cdn-surge.list https://ruleset.skk.moe/List/non_ip/cdn.conf'
               'download-surge.list https://ruleset.skk.moe/List/non_ip/download.conf'
               'speedtest-domains.list https://ruleset.skk.moe/Clash/domainset/speedtest.txt'
+              'apple-cn-special.list https://ruleset.skk.moe/Clash/non_ip/apple_cn.txt'
+              'apple-cn.list https://github.com/felixonmars/dnsmasq-china-list/raw/refs/heads/master/apple.china.conf'
+              'cn.list https://github.com/felixonmars/dnsmasq-china-list/raw/refs/heads/master/accelerated-domains.china.conf'
               'DMCA-Sensitive.list https://github.com/LM-Firefly/Rules/raw/refs/heads/master/Special/DMCA-Sensitive.list'
               'trackers-XIU2.list https://github.com/XIU2/TrackersListCollection/raw/refs/heads/master/all.txt'
               'trackers-ngosang.list https://github.com/ngosang/trackerslist/raw/refs/heads/master/trackers_all.txt'
               'applications-yaml.list https://github.com/Loyalsoldier/clash-rules/raw/refs/heads/release/applications.txt'
               'fake-ip-filter.list https://github.com/juewuy/ShellCrash/raw/refs/heads/dev/public/fake_ip_filter.list'
-              'chinadomains.list https://github.com/felixonmars/dnsmasq-china-list/raw/refs/heads/master/accelerated-domains.china.conf'
-              'direct-need-to-remove.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/master/resouces/direct-need-to-remove.txt'
           )
           counter=0
           for file in "${files[@]}"; do
               set -- $file
-              if [ "$counter" -ge 0 ] && [ "$counter" -le 4 ]; then
+              if [ "$counter" -ge 0 ] && [ "$counter" -le 5 ]; then
                   curl -f -L "$2" | sed -e '/this_ruleset_is_made_by_sukkaw.ruleset.skk.moe/d' -e '$a\' > "download/special/$1" || { echo "Download Failed: $1"; exit 1; }
+              elif [ "$counter" -ge 6 ] && [ "$counter" -le 7 ]; then
+                  curl -f -L "$2" | sed '$a\' | awk '{gsub(/^server=\//, "DOMAIN-SUFFIX,"); gsub(/\/114\.114\.114\.114$/, ""); print}' > "download/special/$1" || { echo "Download Failed: $1"; exit 1; }
               else
                   curl -f -L "$2" | sed '$a\' > "download/special/$1" || { echo "Download Failed: $1"; exit 1; }
               fi
@@ -124,8 +128,8 @@ jobs:
           src_dir="download/meta"
           dst_dir="surge"
 
-          src_names=('iplocation-direct' 'iplocation-proxy' 'douyin' 'talkatone' 'apple@cn' 'microsoft@cn' 'tld-!cn' 'cncidr')
-          dst_names=('iplocation-direct' 'iplocation-proxy' 'douyin' 'talkatone' 'apple-cn' 'microsoft-cn' 'tld-proxy' 'cncidr')
+          src_names=('iplocation-direct' 'iplocation-proxy' 'douyin' 'talkatone' 'microsoft@cn' 'tld-!cn' 'cncidr')
+          dst_names=('iplocation-direct' 'iplocation-proxy' 'douyin' 'talkatone' 'microsoft-cn' 'tld-proxy' 'cncidr')
 
           for i in "${!dst_names[@]}"; do
               src_file="$src_dir/${src_names[i]}.list"
@@ -172,6 +176,12 @@ jobs:
         run: |
           awk '{sub(/,extended-matching$/, ""); print}' 'download/surge/AppleNoChinaCDN.list' >> 'download/surge/AppleProxy.list'
           cp 'download/surge/AppleProxy.list' 'surge/apple-proxy.list'
+
+      - name: Merge apple-cn file
+        run: |
+          cat 'download/special/apple-cn-special.list' \
+              'download/special/apple-cn.list' \
+          > surge/apple-cn.list
 
       - name: Merge games-cn file
         run: |
@@ -257,32 +267,32 @@ jobs:
 
       - name: Merge cdn file
         run: |
-          awk '/^\s*[#;]/ { next } /^$/ { next } { sub(" //.*", ""); if ($0 ~ /^\+\./) print "DOMAIN-SUFFIX," substr($0, 3); else print "DOMAIN," $0; }' 'download/special/cdn-domains.list' > 'download/special/cdn-classical.list'
+          awk '/^\s*[#;]/ { next } /^$/ { next } { sub(" //.*", ""); if ($0 ~ /^\+\./) print "DOMAIN-SUFFIX," substr($0, 3); else print "DOMAIN," $0; }' 'download/special/cdn-domains.list' > 'cdn-classical.list'
 
-          awk '/^\s*[#;]/ { next } /^$/ { next } { sub(" //.*", ""); if ($0 ~ /^\+\./) print "DOMAIN-SUFFIX," substr($0, 3); else print "DOMAIN," $0; }' 'download/special/download-domains.list' > 'download/special/download-classical.list'
+          awk '/^\s*[#;]/ { next } /^$/ { next } { sub(" //.*", ""); if ($0 ~ /^\+\./) print "DOMAIN-SUFFIX," substr($0, 3); else print "DOMAIN," $0; }' 'download/special/download-domains.list' > 'download-classical.list'
 
-          cat 'download/special/cdn-classical.list' \
+          cat 'cdn-classical.list' \
+              'download-classical.list' \
               'download/special/cdn-surge.list' \
-              'download/special/download-classical.list' \
               'download/special/download-surge.list' \
           > surge/cdn.list
 
       - name: Merge speedtest file
         run: |
-          cat <<EOF > download/special/ipv6test.list
+          cat <<EOF > ipv6test.list
           DOMAIN-SUFFIX,ipv6-test.com
           DOMAIN-SUFFIX,ipv6test.com
           DOMAIN-SUFFIX,test-ipv6.com
           DOMAIN-SUFFIX,testipv6.com
           EOF
 
-          awk '/^\s*[#;]/ { next } /^$/ { next } { sub(" //.*", ""); if ($0 ~ /^\+\./) print "DOMAIN-SUFFIX," substr($0, 3); else print "DOMAIN," $0; }' 'download/special/speedtest-domains.list' > 'download/special/speedtest-classical.list'
+          awk '/^\s*[#;]/ { next } /^$/ { next } { sub(" //.*", ""); if ($0 ~ /^\+\./) print "DOMAIN-SUFFIX," substr($0, 3); else print "DOMAIN," $0; }' 'download/special/speedtest-domains.list' > 'speedtest-classical.list'
 
-          cat 'download/meta/speedtest.list' \
+          cat 'ipv6test.list' \
+              'speedtest-classical.list' \
+              'download/meta/speedtest.list' \
               'download/meta/SpeedTest.list' \
               'download/surge/Speedtest.list' \
-              'download/special/speedtest-classical.list' \
-              'download/special/ipv6test.list' \
           > surge/speedtest.list
 
       - name: Merge gfw file
@@ -294,14 +304,17 @@ jobs:
 
       - name: Merge proxy file
         run: |
-          cat 'surge/gfw.list' \
+          grep -vxF -f 'surge/tld-proxy.list' 'download/surge/global.list' > 'global.list'
+          cat 'global.list' \
+              'surge/gfw.list' \
               'download/meta/geolocation-!cn.list' \
               'download/surge/Proxy.list' \
+              'custom/proxy.list' \
           > surge/proxy.list
 
       - name: Merge private file
         run: |
-          cat <<EOF > download/special/panels.list
+          cat <<EOF > panels.list
           DOMAIN,yacd.haishan.me
           DOMAIN,yacd.metacubex.one
           DOMAIN,d.metacubex.one
@@ -310,7 +323,7 @@ jobs:
           DOMAIN,board.zash.run.place
           EOF
 
-          cat 'download/special/panels.list' \
+          cat 'panels.list' \
               'download/meta/private.list' \
               'download/surge/Lan.list' \
           > surge/private.list
@@ -319,21 +332,21 @@ jobs:
         run: |
           cat 'download/special/trackers-XIU2.list' \
               'download/special/trackers-ngosang.list' \
-          > 'download/special/trackers.list'
+          > 'trackers.list'
 
-          grep -oP '([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}' 'download/special/trackers.list'| sed 's/^/DOMAIN,/' > 'download/special/tracker_domains.list'
+          grep -oP '([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}' 'trackers.list'| sed 's/^/DOMAIN,/' > 'tracker_domains.list'
 
-          grep -oP '([0-9]{1,3}\.){3}[0-9]{1,3}' 'download/special/trackers.list' | sed 's/^/IP-CIDR,/; s/$/\/32/' > 'download/special/trackersV4.list'
+          grep -oP '([0-9]{1,3}\.){3}[0-9]{1,3}' 'trackers.list' | sed 's/^/IP-CIDR,/; s/$/\/32/' > 'trackersV4.list'
 
-          grep -oP '(?<=\[).*?(?=\])' 'download/special/trackers.list' | sed 's/^/IP-CIDR6,/; s/$/\/128/' > 'download/special/trackersV6.list'
+          grep -oP '(?<=\[).*?(?=\])' 'trackers.list' | sed 's/^/IP-CIDR6,/; s/$/\/128/' > 'trackersV6.list'
 
-          grep -v 'payload:' 'download/special/applications-yaml.list' | sed -e 's/^[ \t]*- //' > 'download/special/applications.list'
+          grep -v 'payload:' 'download/special/applications-yaml.list' | sed -e 's/^[ \t]*- //' > 'applications.list'
 
-          cat 'download/special/DMCA-Sensitive.list' \
-              'download/special/tracker_domains.list' \
-              'download/special/trackersV4.list' \
-              'download/special/trackersV6.list' \
-              'download/special/applications.list' \
+          cat 'tracker_domains.list' \
+              'trackersV4.list' \
+              'trackersV6.list' \
+              'applications.list' \
+              'download/special/DMCA-Sensitive.list' \
               'download/meta/category-pt.list' \
               'download/meta/tracker.list' \
               'download/surge/Download.list' \
@@ -348,12 +361,9 @@ jobs:
               sort -u "${file}" | domain_dedupe | ruleset_sort > tmp.list && mv tmp.list "${file}"
           done
 
-          awk '{gsub(/^server=\//, "DOMAIN-SUFFIX,"); gsub(/\/114\.114\.114\.114$/, ""); print}' 'download/special/chinadomains.list' > 'tmp-chinadomains.list'
-          awk '{print "DOMAIN-SUFFIX," $0}' 'download/special/direct-need-to-remove.list' > 'tmp-remove.list'
-
-          sort 'tmp-chinadomains.list' 'download/meta/cn.list' | uniq > without-redundant-cn.list
-          sort 'tmp-remove.list' 'surge/tld-proxy.list' 'surge/cdn.list' 'surge/proxy.list' | uniq > remove.list
-          sort 'without-redundant-cn.list' 'remove.list' | uniq | domain_dedupe | grep -vxF -f 'remove.list' | ruleset_sort > 'surge/cn.list'
+          sort 'download/special/cn.list' 'download/meta/cn.list' | uniq > cn-without-redundant.list
+          sort 'custom/direct-need-to-remove.list' 'surge/tld-proxy.list' 'surge/cdn.list' 'surge/proxy.list' | uniq > remove.list
+          sort 'cn-without-redundant.list' 'remove.list' | uniq | domain_dedupe | grep -vxF -f 'remove.list' | ruleset_sort > 'surge/cn.list'
 
       - name: Generate meta ruleset
         run: |
