Chore: update workflow

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -15,13 +15,32 @@ jobs:
       - name: Set variables
         run: |
           echo "update_version=$(date -d '+8 hours' +%Y-%m-%d)" >> ${GITHUB_ENV}
-          echo "mihomo_domains=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/classical" >> ${GITHUB_ENV}
-          echo "mihomo_ipcidr=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/classical" >> ${GITHUB_ENV}
-          echo "bm7_surge=https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Surge" >> ${GITHUB_ENV}
+          echo "mihomo_domains=meta-rules/geo/geosite/classical" >> ${GITHUB_ENV}
+          echo "mihomo_ipcidr=meta-rules/geo/geoip/classical" >> ${GITHUB_ENV}
+          echo "bm7_surge=bm7-rules/rule/Surge" >> ${GITHUB_ENV}
         shell: bash
 
       - name: Checkout Repo
         uses: actions/checkout@v4
+
+      - name: Checkout 'MetaCubeX/meta-rules-dat'
+        uses: actions/checkout@v4
+        with:
+          repository: 'MetaCubeX/meta-rules-dat'
+          ref: meta
+          path: 'meta-rules'
+          sparse-checkout: |
+            geo/geosite/classical
+            geo/geoip/classical
+
+      - name: Checkout 'blackmatrix7/ios_rule_script'
+        uses: actions/checkout@v4
+        with:
+          repository: 'blackmatrix7/ios_rule_script'
+          ref: master
+          path: 'bm7-rules'
+          sparse-checkout: |
+            rule/Surge
 
       - name: Generate directories
         run: |
@@ -45,10 +64,8 @@ jobs:
           domain_lists=('category-httpdns-cn' 'apple' 'microsoft@cn' 'onedrive' 'microsoft' 'github' 'gitlab' 'gitee' 'gitbook' 'apple-intelligence' 'category-ai-!cn' 'amazon' 'shopify' 'category-ecommerce' 'paypal' 'wise' 'category-cryptocurrency' 'category-game-accelerator-cn' 'category-games@cn' 'category-games' 'category-forums' 'discord' 'line' 'telegram' 'twitter' 'signal' 'meta' 'tiktok' 'bilibili' 'googlefcm' 'youtube' 'google' 'spotify' 'twitch' 'bahamut' 'hbo' 'disney' 'primevideo' 'netflix' 'hulu' 'abema' 'dmm' 'niconico' 'apple-tvplus' 'dazn' 'mytvsuper' 'speedtest' 'tld-!cn' 'category-public-tracker' 'tracker' 'category-anticensorship' 'gfw' 'private' 'nga' 'xiaohongshu' 'sina' 'zhihu' 'douban' 'coolapk')
 
           for list in "${domain_lists[@]}"; do
-              echo "${list}.list" "${mihomo_domains}/${list}.list"
-          done | xargs -n 2 -P 5 sh -c '
-              curl -f -L -o download/meta/$0 "$1" || { echo "Download Failed: $0"; exit 1; }
-          '
+              cp "${mihomo_domains}/${list}.list" "download/meta/${list}.list"
+          done
 
           for file in download/meta/*.list; do
               if [ -f "$file" ]; then
@@ -59,10 +76,8 @@ jobs:
           ipcidr_lists=('facebook' 'telegram' 'twitter' 'google' 'netflix' 'private')
 
           for list in "${ipcidr_lists[@]}"; do
-              echo "${list}.list" "${mihomo_ipcidr}/${list}.list"
-          done | xargs -n 2 -P 5 sh -c '
-              curl -f -L "$1" >> download/meta/$0 || { echo "Download Failed: $0"; exit 1; }
-          '
+              cat "${mihomo_ipcidr}/${list}.list" >> "download/meta/${list}.list"
+          done
 
           files=(
               'cncidr.list https://github.com/Loyalsoldier/geoip/raw/refs/heads/release/surge/cn.txt'
@@ -78,10 +93,9 @@ jobs:
           )
 
           for file in "${files[@]}"; do
-              echo "$file"
-          done | xargs -n 2 -P 5 sh -c '
-              curl -f -L -o download/meta/$0 "$1" || { echo "Download Failed: $0"; exit 1; }
-          '
+                set -- $file
+                curl -f -L -H "Accept-Language: en-us" "$2" > "download/meta/$1" || { echo "Download Failed: $1"; exit 1; }
+          done
 
           sed -n '/## >> 抖音/,/##/{//!p}' "download/meta/douyin.list" > tmp.list && mv tmp.list "download/meta/douyin.list"
 
@@ -95,17 +109,25 @@ jobs:
           surge_lists=('AppleProxy' 'Download' 'OneDrive' 'Microsoft' 'GitHub' 'GitLab' 'Gitee' 'GitBook' 'Amazon' 'eBay' 'Shopee' 'Shopify' 'PayPal' 'Crypto' 'Cryptocurrency' 'SteamCN' 'Game' 'Reddit' 'Discord' 'Whatsapp' 'Line' 'Threads' 'Instagram' 'Facebook' 'Twitter' 'TikTok' 'BiliBili' 'GoogleFCM' 'YouTube' 'Google' 'Spotify' 'Twitch' 'Bahamut' 'HBO' 'Disney' 'PrimeVideo' 'Netflix' 'Hulu' 'Abema' 'DMM' 'Niconico' 'AppleTV' 'DAZN' 'myTVSUPER' 'Speedtest' 'Lan' 'NGA' 'XiaoHongShu' 'Weibo' 'Zhihu' 'DouBan' 'Coolapk' 'DouYin')
 
           for list in "${surge_lists[@]}"; do
-              echo "${list}.list" "${bm7_surge}/${list}/${list}.list"
-          done | xargs -n 2 -P 5 sh -c '
-              curl -f -L -o download/surge/$0 "$1" || { echo "Download Failed: $0"; exit 1; }
-          '
+              cp "${bm7_surge}/${list}/${list}.list" "download/surge/${list}.list"
+          done
+
+          surge_game_lists=('GameDownloadCN' 'GameDownload')
+
+          for list in "${surge_game_lists[@]}"; do
+              cp "${bm7_surge}/Game/${list}/${list}.list" "download/surge/${list}.list"
+          done
+
+          surge_all_src_names=('Apple' 'Proxy' 'Global')
+          surge_all_dst_names=('Apple' 'GFW' 'Proxy')
+
+          for i in "${!surge_all_dst_names[@]}"; do
+              src_file="${bm7_surge}/${surge_all_src_names[i]}/${surge_all_src_names[i]}_All.list"
+              dst_file="download/surge/${surge_all_dst_names[i]}.list"
+              cp "$src_file" "$dst_file"
+          done
 
           files=(
-              'GameDownloadCN.list https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Surge/Game/GameDownloadCN/GameDownloadCN.list'
-              'GameDownload.list https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Surge/Game/GameDownload/GameDownload.list'
-              'Apple.list https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Surge/Apple/Apple_All.list'
-              'GFW.list https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Surge/Proxy/Proxy_All.list'
-              'Proxy.list https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Surge/Global/Global_All.list'
               'apple-proxy.list https://github.com/Elysian-Realme/FuGfConfig/raw/refs/heads/main/ConfigFile/Loon/Apple/no-cn-cdn-domain.list'
               'httpdns.list https://github.com/VirgilClyne/GetSomeFries/raw/refs/heads/main/ruleset/HTTPDNS.Block.list'
               'pcdn.list https://github.com/uselibrary/PCDN/raw/refs/heads/main/pcdn.list'
@@ -115,10 +137,9 @@ jobs:
           )
 
           for file in "${files[@]}"; do
-              echo "$file"
-          done | xargs -n 2 -P 5 sh -c '
-              curl -f -L -o download/surge/$0 "$1" || { echo "Download Failed: $0"; exit 1; }
-          '
+                set -- $file
+                curl -f -L -H "Accept-Language: en-us" "$2" > "download/surge/$1" || { echo "Download Failed: $1"; exit 1; }
+          done
 
           for file in download/surge/*.list; do
               awk "{ gsub(/[[:cntrl:]]/, \"\", \$0) } { gsub(/[^:]\/\/.*/, \"\", \$0) } { gsub(/ /, \"\", \$0) } /^\s*[#;]/ { next } /^$/ { next } { print \$0 } END { print \"\" }" "$file" > tmp.list && mv tmp.list "${file}"
@@ -150,10 +171,9 @@ jobs:
           )
 
           for file in "${files[@]}"; do
-              echo "$file"
-          done | xargs -n 2 -P 5 sh -c '
-              curl -f -L -o download/special/$0 "$1" || { echo "Download Failed: $0"; exit 1; }
-          '
+                set -- $file
+                curl -f -L -H "Accept-Language: en-us" "$2" > "download/special/$1" || { echo "Download Failed: $1"; exit 1; }
+          done
 
           for file in download/special/*.list; do
               awk "{ gsub(/[[:cntrl:]]/, \"\", \$0) } { gsub(/[^:]\/\/.*/, \"\", \$0) } { gsub(/ /, \"\", \$0) } /^\s*[#;]/ { next } /^$/ { next } { print \$0 } END { print \"\" }" "$file" > tmp.list && mv tmp.list "${file}"
